"""Initial tables

Revision ID: 0121832f6768
Revises: 
Create Date: 2026-01-22 17:40:07.066718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0121832f6768'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abc_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ABC_category', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_abc_list')),
    sa.UniqueConstraint('ABC_category', name=op.f('uq_abc_list_ABC_category'))
    )
    op.create_table('delivery_to_customer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Customer_name', sa.String(), nullable=True),
    sa.Column('Delivery_date', sa.Date(), nullable=True),
    sa.Column('Bill', sa.String(), nullable=True),
    sa.Column('Customer_in_logist', sa.String(), nullable=True),
    sa.Column('INN', sa.String(), nullable=True),
    sa.Column('Carrier', sa.String(), nullable=True),
    sa.Column('Sborka', sa.String(), nullable=True),
    sa.Column('Delivery_method', sa.String(), nullable=True),
    sa.Column('Delivery_amount_w_VAT', sa.Numeric(), nullable=True),
    sa.Column('Delivery_amount_wo_VAT', sa.Numeric(), nullable=True),
    sa.Column('Order_volume', sa.Numeric(), nullable=True),
    sa.Column('Comment', sa.String(), nullable=True),
    sa.Column('OZON', sa.String(), nullable=True),
    sa.Column('TS', sa.String(), nullable=True),
    sa.Column('CD_per_lt', sa.Numeric(), nullable=True),
    sa.Column('new_Amount', sa.Numeric(), nullable=True),
    sa.Column('check_Deliv_amount', sa.String(), nullable=True),
    sa.Column('inv_Volume', sa.Numeric(), nullable=True),
    sa.Column('check_Inv_volume', sa.String(), nullable=True),
    sa.Column('Invoice', sa.String(), nullable=True),
    sa.Column('Invoice_date', sa.Date(), nullable=True),
    sa.Column('Year_delivery', sa.Integer(), nullable=True),
    sa.Column('Bill_and_Date', sa.String(), nullable=True),
    sa.Column('new_Comment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery_to_customer'))
    )
    op.create_index('idx_delivery_bill', 'delivery_to_customer', ['Bill'], unique=False)
    op.create_index('idx_delivery_bill_sborka', 'delivery_to_customer', ['Bill', 'Sborka'], unique=False)
    op.create_index('idx_delivery_customer_name', 'delivery_to_customer', ['Customer_name'], unique=False)
    op.create_index('idx_delivery_delivery_date', 'delivery_to_customer', ['Delivery_date'], unique=False)
    op.create_index('idx_delivery_inn', 'delivery_to_customer', ['INN'], unique=False)
    op.create_index('idx_delivery_sborka', 'delivery_to_customer', ['Sborka'], unique=False)
    op.create_table('delivery_to_customer_24',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Customer_name', sa.String(), nullable=True),
    sa.Column('Delivery_date', sa.Date(), nullable=True),
    sa.Column('Bill', sa.String(), nullable=True),
    sa.Column('Customer_in_logist', sa.String(), nullable=True),
    sa.Column('INN', sa.String(), nullable=True),
    sa.Column('Carrier', sa.String(), nullable=True),
    sa.Column('Sborka', sa.String(), nullable=True),
    sa.Column('Delivery_method', sa.String(), nullable=True),
    sa.Column('Delivery_amount_w_VAT', sa.Numeric(), nullable=True),
    sa.Column('Delivery_amount_wo_VAT', sa.Numeric(), nullable=True),
    sa.Column('Order_volume', sa.Numeric(), nullable=True),
    sa.Column('Comment', sa.String(), nullable=True),
    sa.Column('OZON', sa.String(), nullable=True),
    sa.Column('TS', sa.String(), nullable=True),
    sa.Column('CD_per_lt', sa.Numeric(), nullable=True),
    sa.Column('new_Amount', sa.Numeric(), nullable=True),
    sa.Column('check_Deliv_amount', sa.String(), nullable=True),
    sa.Column('inv_Volume', sa.Numeric(), nullable=True),
    sa.Column('check_Inv_volume', sa.String(), nullable=True),
    sa.Column('Invoice', sa.String(), nullable=True),
    sa.Column('Invoice_date', sa.Date(), nullable=True),
    sa.Column('Year_delivery', sa.Integer(), nullable=True),
    sa.Column('Bill_and_Date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery_to_customer_24'))
    )
    op.create_index('idx_delivery24_bill', 'delivery_to_customer_24', ['Bill'], unique=False)
    op.create_index('idx_delivery24_bill_sborka', 'delivery_to_customer_24', ['Bill', 'Sborka'], unique=False)
    op.create_index('idx_delivery24_customer_name', 'delivery_to_customer_24', ['Customer_name'], unique=False)
    op.create_index('idx_delivery24_delivery_date', 'delivery_to_customer_24', ['Delivery_date'], unique=False)
    op.create_index('idx_delivery24_inn', 'delivery_to_customer_24', ['INN'], unique=False)
    op.create_index('idx_delivery24_sborka', 'delivery_to_customer_24', ['Sborka'], unique=False)
    op.create_table('doc_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Document', sa.String(), nullable=True),
    sa.Column('Transaction', sa.String(), nullable=True),
    sa.Column('Doc_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doc_type'))
    )
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Holding_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holdings')),
    sa.UniqueConstraint('Holding_name', name=op.f('uq_holdings_Holding_name'))
    )
    op.create_table('product_family',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('Product_family', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_family'))
    )
    op.create_table('quarters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Quarter', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quarters'))
    )
    op.create_table('sectors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Sector_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sectors')),
    sa.UniqueConstraint('Sector_name', name=op.f('uq_sectors_Sector_name'))
    )
    op.create_table('suppliers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('Supplier_Name', sa.String(), nullable=True),
    sa.Column('Full_Suppl_name', sa.String(), nullable=True),
    sa.Column('Imp_Loc', sa.String(), nullable=True),
    sa.Column('Customs', sa.String(), nullable=True),
    sa.Column('Movement', sa.String(), nullable=True),
    sa.Column('Country', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers'))
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Team', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team'))
    )
    op.create_table('tnved',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tnved')),
    sa.UniqueConstraint('code', name=op.f('uq_tnved_code'))
    )
    op.create_table('weeks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Week_of_Year', sa.Integer(), nullable=False),
    sa.Column('Week_of_Month', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weeks'))
    )
    op.create_table('years',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_years')),
    sa.UniqueConstraint('Year', name=op.f('uq_years_Year'))
    )
    op.create_table('add_suppl_cost',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Document', sa.String(), nullable=True),
    sa.Column('Date', sa.Date(), nullable=True),
    sa.Column('Supplier_id', sa.String(), nullable=True),
    sa.Column('Supplier_Name_report', sa.String(), nullable=True),
    sa.Column('Supplier1', sa.String(), nullable=True),
    sa.Column('Supplier2', sa.String(), nullable=True),
    sa.Column('Order', sa.String(), nullable=True),
    sa.Column('Shipment', sa.String(), nullable=True),
    sa.Column('Container', sa.String(), nullable=True),
    sa.Column('Suppl_Inv_N', sa.String(), nullable=True),
    sa.Column('Storage', sa.String(), nullable=True),
    sa.Column('Imp_Loc', sa.String(), nullable=True),
    sa.Column('Movement', sa.String(), nullable=True),
    sa.Column('Bonus', sa.String(), nullable=True),
    sa.Column('Labling_Stock', sa.String(), nullable=True),
    sa.Column('Volume', sa.Numeric(), nullable=True),
    sa.Column('First_Invoice_Amount', sa.Numeric(), nullable=True),
    sa.Column('Final_Invoice_Amount', sa.Numeric(), nullable=True),
    sa.Column('GTD_doc', sa.String(), nullable=True),
    sa.Column('Status', sa.String(), nullable=True),
    sa.Column('Currency', sa.String(), nullable=True),
    sa.Column('Payment_FX', sa.Numeric(), nullable=True),
    sa.Column('Load_Unload', sa.Numeric(), nullable=True),
    sa.Column('Commission', sa.Numeric(), nullable=True),
    sa.Column('Agency', sa.Numeric(), nullable=True),
    sa.Column('Transport_mn', sa.Numeric(), nullable=True),
    sa.Column('Transport_loc', sa.Numeric(), nullable=True),
    sa.Column('Add_Services', sa.Numeric(), nullable=True),
    sa.Column('Comment', sa.String(), nullable=True),
    sa.Column('Transp_VED', sa.Numeric(), nullable=True),
    sa.Column('Customs_date', sa.Date(), nullable=True),
    sa.Column('Date_arrival', sa.Date(), nullable=True),
    sa.Column('Carrier', sa.String(), nullable=True),
    sa.Column('Carrier_orders', sa.String(), nullable=True),
    sa.Column('merge_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['Supplier_id'], ['suppliers.id'], name=op.f('fk_add_suppl_cost_Supplier_id_suppliers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_add_suppl_cost')),
    sa.UniqueConstraint('merge_id', name=op.f('uq_add_suppl_cost_merge_id'))
    )
    op.create_table('customers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('Customer_code', sa.String(), nullable=True),
    sa.Column('Customer_name', sa.String(), nullable=True),
    sa.Column('INN', sa.String(), nullable=True),
    sa.Column('Price_type', sa.String(), nullable=True),
    sa.Column('Region', sa.String(), nullable=True),
    sa.Column('City', sa.String(), nullable=True),
    sa.Column('Sector_id', sa.Integer(), nullable=True),
    sa.Column('Holding_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Holding_id'], ['holdings.id'], name='fk_customer_holding'),
    sa.ForeignKeyConstraint(['Sector_id'], ['sectors.id'], name='fk_customer_sector'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    op.create_table('customs_rate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TNVED_id', sa.Integer(), nullable=True),
    sa.Column('Cust_rate', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['TNVED_id'], ['tnved.id'], name='fk_customs_rate_tnved'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customs_rate'))
    )
    op.create_table('ecofee_amount',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('merge', sa.String(), nullable=True),
    sa.Column('TNVED_id', sa.Integer(), nullable=True),
    sa.Column('year_id', sa.Integer(), nullable=True),
    sa.Column('ECO_amount', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['TNVED_id'], ['tnved.id'], name='fk_ecofee_amount_tnved'),
    sa.ForeignKeyConstraint(['year_id'], ['years.id'], name='fk_ecofee_amount_year'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ecofee_amount')),
    sa.UniqueConstraint('merge', name=op.f('uq_ecofee_amount_merge'))
    )
    op.create_table('ecofee_standard',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('merge', sa.String(), nullable=True),
    sa.Column('TNVED_id', sa.Integer(), nullable=True),
    sa.Column('year_id', sa.Integer(), nullable=True),
    sa.Column('ECO_standard', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['TNVED_id'], ['tnved.id'], name='fk_ecofee_standard_tnved'),
    sa.ForeignKeyConstraint(['year_id'], ['years.id'], name='fk_ecofee_standard_year'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ecofee_standard')),
    sa.UniqueConstraint('merge', name=op.f('uq_ecofee_standard_merge'))
    )
    op.create_table('months',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Month', sa.Integer(), nullable=False),
    sa.Column('Quarter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Quarter_id'], ['quarters.id'], name='fk_months_Quarter_id_quarters'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_months'))
    )
    op.create_table('product_group',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('Product_name', sa.String(), nullable=True),
    sa.Column('TNVED_id', sa.Integer(), nullable=True),
    sa.Column('Product_Family_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['Product_Family_id'], ['product_family.id'], name='fk_product_group_family'),
    sa.ForeignKeyConstraint(['TNVED_id'], ['tnved.id'], name='fk_product_group_tnved'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_group'))
    )
    op.create_table('stls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('STL_name', sa.String(), nullable=True),
    sa.Column('Email', sa.String(), nullable=True),
    sa.Column('Has_report', sa.String(), nullable=True),
    sa.Column('Report_link', sa.String(), nullable=True),
    sa.Column('Template', sa.String(), nullable=True),
    sa.Column('Team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Team_id'], ['team.id'], name='fk_stl_team'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stls'))
    )
    op.create_table('suppl_schemes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Supplier1', sa.String(), nullable=True),
    sa.Column('Country', sa.String(), nullable=True),
    sa.Column('Supplier2', sa.String(), nullable=True),
    sa.Column('Supplier_id', sa.String(), nullable=True),
    sa.Column('Supplier_Name_report', sa.String(), nullable=True),
    sa.Column('Agency', sa.Numeric(), nullable=True),
    sa.Column('Re_export', sa.Numeric(), nullable=True),
    sa.Column('Delivery', sa.Numeric(), nullable=True),
    sa.Column('Comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['Supplier_id'], ['suppliers.id'], name='fk_scheme_supplier'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppl_schemes')),
    sa.UniqueConstraint('Supplier_Name_report', name=op.f('uq_suppl_schemes_Supplier_Name_report'))
    )
    op.create_table('team_leads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TeamLead_name', sa.String(), nullable=True),
    sa.Column('Email', sa.String(), nullable=True),
    sa.Column('Has_report', sa.String(), nullable=True),
    sa.Column('Report_link', sa.String(), nullable=True),
    sa.Column('Template', sa.String(), nullable=True),
    sa.Column('Team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Team_id'], ['team.id'], name='fk_teamlead_team'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_leads'))
    )
    op.create_table('calendar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Day', sa.Date(), nullable=False),
    sa.Column('Year_id', sa.Integer(), nullable=False),
    sa.Column('Quarter_id', sa.Integer(), nullable=False),
    sa.Column('Month_id', sa.Integer(), nullable=False),
    sa.Column('Week_id', sa.Integer(), nullable=False),
    sa.Column('NETWORKDAYS', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Month_id'], ['months.id'], name='fk_calendar_Month_id_months'),
    sa.ForeignKeyConstraint(['Quarter_id'], ['quarters.id'], name='fk_calendar_Quarter_id_quarters'),
    sa.ForeignKeyConstraint(['Week_id'], ['weeks.id'], name='fk_calendar_Week_id_weeks'),
    sa.ForeignKeyConstraint(['Year_id'], ['years.id'], name='fk_calendar_Year_id_years'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar')),
    sa.UniqueConstraint('Day', name=op.f('uq_calendar_Day'))
    )
    op.create_table('company_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Work_Days', sa.Integer(), nullable=True),
    sa.Column('Month_vol', sa.Numeric(), nullable=True),
    sa.Column('Month_Revenue', sa.Numeric(), nullable=True),
    sa.Column('Month_Margin', sa.Numeric(), nullable=True),
    sa.Column('Volume_Target_total', sa.Numeric(), nullable=True),
    sa.Column('Revenue_Target_total', sa.Numeric(), nullable=True),
    sa.Column('Margin_Target_total', sa.Numeric(), nullable=True),
    sa.Column('Status', sa.String(), nullable=True),
    sa.Column('Year_id', sa.Integer(), nullable=True),
    sa.Column('Month_id', sa.Integer(), nullable=True),
    sa.Column('Week_id', sa.Integer(), nullable=True),
    sa.Column('TeamLead_id', sa.Integer(), nullable=True),
    sa.Column('ABC_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ABC_category_id'], ['abc_list.id'], name='fk_company_plans_ABC_category_id_abc_list'),
    sa.ForeignKeyConstraint(['Month_id'], ['months.id'], name='fk_company_plans_Month_id_months'),
    sa.ForeignKeyConstraint(['TeamLead_id'], ['team_leads.id'], name='fk_company_plans_TeamLead_id_team_leads'),
    sa.ForeignKeyConstraint(['Week_id'], ['weeks.id'], name='fk_company_plans_Week_id_weeks'),
    sa.ForeignKeyConstraint(['Year_id'], ['years.id'], name='fk_company_plans_Year_id_years'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_plans'))
    )
    op.create_table('labling',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year_id', sa.Integer(), nullable=True),
    sa.Column('month_id', sa.Integer(), nullable=True),
    sa.Column('чехов_1', sa.Numeric(), nullable=True),
    sa.Column('чехов_5', sa.Numeric(), nullable=True),
    sa.Column('чехов_25', sa.Numeric(), nullable=True),
    sa.Column('чехов_60', sa.Numeric(), nullable=True),
    sa.Column('чехов_230', sa.Numeric(), nullable=True),
    sa.Column('тлтк_1', sa.Numeric(), nullable=True),
    sa.Column('тлтк_5', sa.Numeric(), nullable=True),
    sa.Column('тлтк_25', sa.Numeric(), nullable=True),
    sa.Column('тлтк_60', sa.Numeric(), nullable=True),
    sa.Column('тлтк_230', sa.Numeric(), nullable=True),
    sa.Column('баррус_1', sa.Numeric(), nullable=True),
    sa.Column('баррус_5', sa.Numeric(), nullable=True),
    sa.Column('баррус_25', sa.Numeric(), nullable=True),
    sa.Column('баррус_60', sa.Numeric(), nullable=True),
    sa.Column('баррус_230', sa.Numeric(), nullable=True),
    sa.Column('дельта_1', sa.Numeric(), nullable=True),
    sa.Column('дельта_5', sa.Numeric(), nullable=True),
    sa.Column('дельта_25', sa.Numeric(), nullable=True),
    sa.Column('дельта_60', sa.Numeric(), nullable=True),
    sa.Column('дельта_230', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['month_id'], ['months.id'], name='fk_labling_month'),
    sa.ForeignKeyConstraint(['year_id'], ['years.id'], name='fk_labling_year'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_labling')),
    sa.UniqueConstraint('year_id', 'month_id', name='uq_labling_year_month')
    )
    op.create_table('managers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Manager_name', sa.String(), nullable=True),
    sa.Column('Email', sa.String(), nullable=True),
    sa.Column('AM_1C_Name', sa.String(), nullable=True),
    sa.Column('Has_report', sa.String(), nullable=True),
    sa.Column('Report_link', sa.String(), nullable=True),
    sa.Column('Template', sa.String(), nullable=True),
    sa.Column('STL_id', sa.Integer(), nullable=True),
    sa.Column('TeamLead_id', sa.Integer(), nullable=True),
    sa.Column('Team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['STL_id'], ['stls.id'], name='fk_manager_stl'),
    sa.ForeignKeyConstraint(['TeamLead_id'], ['team_leads.id'], name='fk_manager_teamlead'),
    sa.ForeignKeyConstraint(['Team_id'], ['team.id'], name='fk_manager_team'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_managers'))
    )
    op.create_table('product_names',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Product_name', sa.String(), nullable=False),
    sa.Column('Product_Group_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['Product_Group_id'], ['product_group.id'], name='fk_product_names_product_group'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_names')),
    sa.UniqueConstraint('Product_name', name=op.f('uq_product_names_Product_name'))
    )
    op.create_table('taxfee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year_id', sa.Integer(), nullable=True),
    sa.Column('month_id', sa.Integer(), nullable=True),
    sa.Column('Excise', sa.Numeric(), nullable=True),
    sa.Column('Customs_clearance', sa.Numeric(), nullable=True),
    sa.Column('Bank_commission', sa.Numeric(), nullable=True),
    sa.Column('Transportation', sa.Numeric(), nullable=True),
    sa.Column('Storage', sa.Numeric(), nullable=True),
    sa.Column('Money_cost', sa.Numeric(), nullable=True),
    sa.Column('Additional_money_percent', sa.Numeric(), nullable=True),
    sa.Column('Lable', sa.Numeric(), nullable=True),
    sa.Column('Okleyka', sa.Numeric(), nullable=True),
    sa.Column('Storage_Teboil', sa.Numeric(), nullable=True),
    sa.Column('Transport_Teboil', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['month_id'], ['months.id'], name='fk_fees_month'),
    sa.ForeignKeyConstraint(['year_id'], ['years.id'], name='fk_fees_year'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taxfee')),
    sa.UniqueConstraint('year_id', 'month_id', name='uq_taxfee_year_month')
    )
    op.create_table('abc_cat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_name_id', sa.Integer(), nullable=True),
    sa.Column('abc_list_id', sa.Integer(), nullable=True),
    sa.Column('Start_date', sa.Date(), nullable=True),
    sa.Column('End_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['abc_list_id'], ['abc_list.id'], name='fk_abc_cat_abc_list'),
    sa.ForeignKeyConstraint(['product_name_id'], ['product_names.id'], name='fk_abc_cat_product_names'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_abc_cat'))
    )
    op.create_table('contracts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('Contract', sa.String(), nullable=True),
    sa.Column('Contract_Type', sa.String(), nullable=True),
    sa.Column('Price_Type', sa.String(), nullable=True),
    sa.Column('Payment_Condition', sa.String(), nullable=True),
    sa.Column('Customer_id', sa.String(), nullable=True),
    sa.Column('Manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Customer_id'], ['customers.id'], name='fk_contract_customer'),
    sa.ForeignKeyConstraint(['Manager_id'], ['managers.id'], name='fk_contract_manager'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contracts'))
    )
    op.create_table('customer_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Volume_Target_cust', sa.Numeric(), nullable=True),
    sa.Column('Revenue_Target_cust', sa.Numeric(), nullable=True),
    sa.Column('Margin_C3_Target_cust', sa.Numeric(), nullable=True),
    sa.Column('Margin_C4_Target_cust', sa.Numeric(), nullable=True),
    sa.Column('Status', sa.String(), nullable=True),
    sa.Column('Year_id', sa.Integer(), nullable=True),
    sa.Column('Month_id', sa.Integer(), nullable=True),
    sa.Column('Week_id', sa.Integer(), nullable=True),
    sa.Column('Holding_id', sa.Integer(), nullable=True),
    sa.Column('Manager_id', sa.Integer(), nullable=True),
    sa.Column('Sector_id', sa.Integer(), nullable=True),
    sa.Column('STL_id', sa.Integer(), nullable=True),
    sa.Column('TeamLead_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Holding_id'], ['holdings.id'], name='fk_customer_plans_Holding_id_holdings'),
    sa.ForeignKeyConstraint(['Manager_id'], ['managers.id'], name='fk_customer_plans_Manager_id_managers'),
    sa.ForeignKeyConstraint(['Month_id'], ['months.id'], name='fk_customer_plans_Month_id_months'),
    sa.ForeignKeyConstraint(['STL_id'], ['stls.id'], name='fk_customer_plans_STL_id_stls'),
    sa.ForeignKeyConstraint(['Sector_id'], ['sectors.id'], name='fk_customer_plans_Sector_id_sectors'),
    sa.ForeignKeyConstraint(['TeamLead_id'], ['team_leads.id'], name='fk_customer_plans_TeamLead_id_team_leads'),
    sa.ForeignKeyConstraint(['Week_id'], ['weeks.id'], name='fk_customer_plans_Week_id_weeks'),
    sa.ForeignKeyConstraint(['Year_id'], ['years.id'], name='fk_customer_plans_Year_id_years'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_plans')),
    sa.UniqueConstraint('Year_id', 'Month_id', 'Week_id', 'Holding_id', 'Manager_id', name='uq_customer_plan_unique')
    )
    op.create_table('hyundai_dealers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Dealer_code', sa.String(), nullable=True),
    sa.Column('Hyundai_code', sa.String(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('City', sa.String(), nullable=True),
    sa.Column('INN', sa.String(), nullable=True),
    sa.Column('Manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Manager_id'], ['managers.id'], name='fk_dealer_manager'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hyundai_dealers')),
    sa.UniqueConstraint('Dealer_code', name=op.f('uq_hyundai_dealers_Dealer_code')),
    sa.UniqueConstraint('Hyundai_code', name=op.f('uq_hyundai_dealers_Hyundai_code'))
    )
    op.create_index('idx_dealer_code_unique', 'hyundai_dealers', ['Dealer_code'], unique=True)
    op.create_index('idx_hyundai_code_unique', 'hyundai_dealers', ['Hyundai_code'], unique=True)
    op.create_table('material',
    sa.Column('Code', sa.String(), nullable=False),
    sa.Column('Article', sa.String(), nullable=True),
    sa.Column('Full_name', sa.String(), nullable=True),
    sa.Column('Brand', sa.String(), nullable=True),
    sa.Column('Family', sa.String(), nullable=True),
    sa.Column('Product_type', sa.String(), nullable=True),
    sa.Column('UoM', sa.String(), nullable=True),
    sa.Column('Report_UoM', sa.String(), nullable=True),
    sa.Column('Package_type', sa.String(), nullable=True),
    sa.Column('Items_per_Package', sa.Integer(), nullable=True),
    sa.Column('Items_per_Set', sa.Integer(), nullable=True),
    sa.Column('Package_Volume', sa.Numeric(), nullable=True),
    sa.Column('Net_weight', sa.Numeric(), nullable=True),
    sa.Column('Gross_weight', sa.Numeric(), nullable=True),
    sa.Column('Density', sa.Numeric(), nullable=True),
    sa.Column('Excise', sa.String(), nullable=True),
    sa.Column('Status', sa.String(), nullable=True),
    sa.Column('Product_Names_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Product_Names_id'], ['product_names.id'], name='fk_materials_product_names'),
    sa.PrimaryKeyConstraint('Code', name=op.f('pk_material'))
    )
    op.create_table('commission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Com_status', sa.String(), nullable=True),
    sa.Column('Start_date', sa.Date(), nullable=True),
    sa.Column('End_date', sa.Date(), nullable=True),
    sa.Column('Comm_perc', sa.Numeric(), nullable=True),
    sa.Column('Comm_rub', sa.Numeric(), nullable=True),
    sa.Column('Comm_Cost_perc', sa.Numeric(), nullable=True),
    sa.Column('Comm_Cost_rub', sa.Numeric(), nullable=True),
    sa.Column('Document', sa.String(), nullable=True),
    sa.Column('Date', sa.Date(), nullable=True),
    sa.Column('Bill', sa.String(), nullable=True),
    sa.Column('Bill_date', sa.Date(), nullable=True),
    sa.Column('Litres_from', sa.Numeric(), nullable=True),
    sa.Column('Litres_to', sa.Numeric(), nullable=True),
    sa.Column('Recipient_code', sa.String(), nullable=True),
    sa.Column('Recipient', sa.String(), nullable=True),
    sa.Column('Hyundai_code', sa.String(), nullable=True),
    sa.Column('Comment', sa.String(), nullable=True),
    sa.Column('Customer_id', sa.String(), nullable=True),
    sa.Column('Material_id', sa.String(), nullable=True),
    sa.Column('Product_group_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['Customer_id'], ['customers.id'], name='fk_commission_customer'),
    sa.ForeignKeyConstraint(['Material_id'], ['material.Code'], name='fk_commission_material'),
    sa.ForeignKeyConstraint(['Product_group_id'], ['product_group.id'], name='fk_commission_product_group'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commission'))
    )
    op.create_table('complects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Date_Time', sa.DateTime(), nullable=True),
    sa.Column('Document', sa.String(), nullable=True),
    sa.Column('Date', sa.Date(), nullable=True),
    sa.Column('Stock', sa.String(), nullable=True),
    sa.Column('Qty', sa.Numeric(), nullable=True),
    sa.Column('DocType_id', sa.Integer(), nullable=True),
    sa.Column('Material_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['DocType_id'], ['doc_type.id'], name='fk_complects_doctype'),
    sa.ForeignKeyConstraint(['Material_id'], ['material.Code'], name='fk_complects_material'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complects'))
    )
    op.create_table('complects_manual',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Date_Time', sa.DateTime(), nullable=True),
    sa.Column('Document', sa.String(), nullable=True),
    sa.Column('Date', sa.Date(), nullable=True),
    sa.Column('Stock', sa.String(), nullable=True),
    sa.Column('Qty', sa.Numeric(), nullable=True),
    sa.Column('DocType_id', sa.Integer(), nullable=True),
    sa.Column('Material_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['DocType_id'], ['doc_type.id'], name='fk_complects_doctype'),
    sa.ForeignKeyConstraint(['Material_id'], ['material.Code'], name='fk_complects_material'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complects_manual'))
    )
    op.create_table('marketplace',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Document', sa.String(), nullable=True),
    sa.Column('Date', sa.Date(), nullable=True),
    sa.Column('Qty', sa.Numeric(), nullable=True),
    sa.Column('Amount_1C', sa.Numeric(), nullable=True),
    sa.Column('Price_1C', sa.Numeric(), nullable=True),
    sa.Column('Payment_terms', sa.String(), nullable=True),
    sa.Column('Post_payment', sa.Numeric(), nullable=True),
    sa.Column('Plan_pay_Date', sa.Date(), nullable=True),
    sa.Column('Stock', sa.String(), nullable=True),
    sa.Column('UoM', sa.String(), nullable=True),
    sa.Column('Currency', sa.String(), nullable=True),
    sa.Column('FX_rate', sa.Numeric(), nullable=True),
    sa.Column('VAT', sa.String(), nullable=True),
    sa.Column('Calendar_id', sa.Integer(), nullable=True),
    sa.Column('Material_id', sa.String(), nullable=True),
    sa.Column('Customer_id', sa.String(), nullable=True),
    sa.Column('Manager_id', sa.Integer(), nullable=True),
    sa.Column('Contract_id', sa.String(), nullable=True),
    sa.Column('Holding_id', sa.Integer(), nullable=True),
    sa.Column('Sector_id', sa.Integer(), nullable=True),
    sa.Column('DocType_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Calendar_id'], ['calendar.id'], name='fk_marketplace_calendar'),
    sa.ForeignKeyConstraint(['Contract_id'], ['contracts.id'], name='fk_marketplace_contract'),
    sa.ForeignKeyConstraint(['Customer_id'], ['customers.id'], name='fk_marketplace_customer'),
    sa.ForeignKeyConstraint(['DocType_id'], ['doc_type.id'], name='fk_marketplace_doctype'),
    sa.ForeignKeyConstraint(['Holding_id'], ['holdings.id'], name='fk_marketplace_holding'),
    sa.ForeignKeyConstraint(['Manager_id'], ['managers.id'], name='fk_marketplace_manager'),
    sa.ForeignKeyConstraint(['Material_id'], ['material.Code'], name='fk_marketplace_material'),
    sa.ForeignKeyConstraint(['Sector_id'], ['sectors.id'], name='fk_marketplace_sector'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marketplace'))
    )
    op.create_index('idx_marketplace_date', 'marketplace', ['Date'], unique=False)
    op.create_index('idx_marketplace_document', 'marketplace', ['Document'], unique=False)
    op.create_index('idx_marketplace_holding', 'marketplace', ['Holding_id'], unique=False)
    op.create_index('idx_marketplace_material', 'marketplace', ['Material_id'], unique=False)
    op.create_table('movements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Date_Time', sa.DateTime(), nullable=True),
    sa.Column('Document', sa.String(), nullable=True),
    sa.Column('Date', sa.Date(), nullable=True),
    sa.Column('Doc_based', sa.String(), nullable=True),
    sa.Column('Date_Doc_based', sa.Date(), nullable=True),
    sa.Column('Stock', sa.String(), nullable=True),
    sa.Column('Qty', sa.Numeric(), nullable=True),
    sa.Column('Recipient_code', sa.String(), nullable=True),
    sa.Column('Recipient', sa.String(), nullable=True),
    sa.Column('Bill', sa.String(), nullable=True),
    sa.Column('Bill_date', sa.Date(), nullable=True),
    sa.Column('DocType_id', sa.Integer(), nullable=True),
    sa.Column('Material_id', sa.String(), nullable=True),
    sa.Column('Customer_id', sa.String(), nullable=True),
    sa.Column('Supplier_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['Customer_id'], ['customers.id'], name='fk_movements_customer'),
    sa.ForeignKeyConstraint(['DocType_id'], ['doc_type.id'], name='fk_movements_doctype'),
    sa.ForeignKeyConstraint(['Material_id'], ['material.Code'], name='fk_movements_material'),
    sa.ForeignKeyConstraint(['Supplier_id'], ['suppliers.id'], name='fk_movements_supplier'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movements'))
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Status', sa.String(), nullable=True),
    sa.Column('Date', sa.Date(), nullable=True),
    sa.Column('Document', sa.String(), nullable=True),
    sa.Column('Supplier1', sa.String(), nullable=True),
    sa.Column('Supplier2', sa.String(), nullable=True),
    sa.Column('Order', sa.String(), nullable=True),
    sa.Column('Shipment', sa.String(), nullable=True),
    sa.Column('VAT', sa.String(), nullable=True),
    sa.Column('Currency', sa.String(), nullable=True),
    sa.Column('Qty', sa.Numeric(), nullable=True),
    sa.Column('Amount_1C', sa.Numeric(), nullable=True),
    sa.Column('Price_1C', sa.Numeric(), nullable=True),
    sa.Column('Qty_pcs', sa.Numeric(), nullable=True),
    sa.Column('Qty_lt', sa.Numeric(), nullable=True),
    sa.Column('Payment_FX', sa.Numeric(), nullable=True),
    sa.Column('Price_pcs_Curr', sa.Numeric(), nullable=True),
    sa.Column('Price_lt_Curr', sa.Numeric(), nullable=True),
    sa.Column('Price_wo_VAT_Rub', sa.Numeric(), nullable=True),
    sa.Column('Amount_wo_VAT_Rub', sa.Numeric(), nullable=True),
    sa.Column('Transport_mn', sa.Numeric(), nullable=True),
    sa.Column('Customs_fee', sa.Numeric(), nullable=True),
    sa.Column('Customs_docs', sa.Numeric(), nullable=True),
    sa.Column('Bank_fee', sa.Numeric(), nullable=True),
    sa.Column('Agency', sa.Numeric(), nullable=True),
    sa.Column('Add_Services', sa.Numeric(), nullable=True),
    sa.Column('ED', sa.Numeric(), nullable=True),
    sa.Column('Eco_fee', sa.Numeric(), nullable=True),
    sa.Column('Movement_fee', sa.Numeric(), nullable=True),
    sa.Column('Load_Unload', sa.Numeric(), nullable=True),
    sa.Column('LPC_purchase_lt', sa.Numeric(), nullable=True),
    sa.Column('LPC_purchase_pcs', sa.Numeric(), nullable=True),
    sa.Column('LPC_purchase_amount', sa.Numeric(), nullable=True),
    sa.Column('Qty_after_spec_order', sa.Numeric(), nullable=True),
    sa.Column('LPC_purchase_after_spec_order', sa.Numeric(), nullable=True),
    sa.Column('Supplier_id', sa.String(), nullable=True),
    sa.Column('Material_id', sa.String(), nullable=True),
    sa.Column('DocType_id', sa.Integer(), nullable=True),
    sa.Column('AddSupplCost_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['AddSupplCost_id'], ['add_suppl_cost.id'], name='fk_purchase_orders_addsupplcost'),
    sa.ForeignKeyConstraint(['DocType_id'], ['doc_type.id'], name='fk_purchase_orders_doctype'),
    sa.ForeignKeyConstraint(['Material_id'], ['material.Code'], name='fk_purchase_orders_material'),
    sa.ForeignKeyConstraint(['Supplier_id'], ['suppliers.id'], name='fk_purchase_orders_supplier'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_orders'))
    )
    op.create_index('idx_purchase_order_material', 'purchase_orders', ['Material_id'], unique=False)
    op.create_index('idx_purchase_order_supplier', 'purchase_orders', ['Supplier_id'], unique=False)
    op.create_table('temp_purchase',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Document', sa.String(), nullable=True),
    sa.Column('Date', sa.Date(), nullable=True),
    sa.Column('Status', sa.String(), nullable=True),
    sa.Column('Doc_based', sa.String(), nullable=True),
    sa.Column('Date_Doc_based', sa.Date(), nullable=True),
    sa.Column('Stock', sa.String(), nullable=True),
    sa.Column('Currency', sa.String(), nullable=True),
    sa.Column('VAT', sa.String(), nullable=True),
    sa.Column('Country', sa.String(), nullable=True),
    sa.Column('GTD', sa.String(), nullable=True),
    sa.Column('FX_rate_1C', sa.Numeric(), nullable=True),
    sa.Column('Qty', sa.Numeric(), nullable=True),
    sa.Column('Amount_1C', sa.Numeric(), nullable=True),
    sa.Column('DocType_id', sa.Integer(), nullable=True),
    sa.Column('Supplier_id', sa.String(), nullable=True),
    sa.Column('Material_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['DocType_id'], ['doc_type.id'], name='fk_temp_purchase_doctype'),
    sa.ForeignKeyConstraint(['Material_id'], ['material.Code'], name='fk_temp_purchase_material'),
    sa.ForeignKeyConstraint(['Supplier_id'], ['suppliers.id'], name='fk_temp_purchase_supplier'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_temp_purchase'))
    )
    op.create_table('temp_sales_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Document', sa.String(), nullable=True),
    sa.Column('Date', sa.Date(), nullable=True),
    sa.Column('Status', sa.String(), nullable=True),
    sa.Column('Bill', sa.String(), nullable=True),
    sa.Column('Bill_Date', sa.Date(), nullable=True),
    sa.Column('Doc_based', sa.String(), nullable=True),
    sa.Column('Date_Doc_based', sa.Date(), nullable=True),
    sa.Column('Stock', sa.String(), nullable=True),
    sa.Column('Delivery_method', sa.String(), nullable=True),
    sa.Column('Currency', sa.String(), nullable=True),
    sa.Column('FX_rate_1C', sa.Numeric(), nullable=True),
    sa.Column('Qty', sa.Numeric(), nullable=True),
    sa.Column('Amount_1C', sa.Numeric(), nullable=True),
    sa.Column('VAT', sa.String(), nullable=True),
    sa.Column('Recipient', sa.String(), nullable=True),
    sa.Column('Recipient_code', sa.String(), nullable=True),
    sa.Column('Days_for_Pay', sa.Numeric(), nullable=True),
    sa.Column('Plan_Pay_Day', sa.Date(), nullable=True),
    sa.Column('Post_payment', sa.Numeric(), nullable=True),
    sa.Column('Payment_term', sa.String(), nullable=True),
    sa.Column('Pay_status', sa.String(), nullable=True),
    sa.Column('Priority', sa.String(), nullable=True),
    sa.Column('Comment', sa.String(), nullable=True),
    sa.Column('Sborka', sa.String(), nullable=True),
    sa.Column('Plan_Delivery_Day', sa.Date(), nullable=True),
    sa.Column('Spec_Order', sa.String(), nullable=True),
    sa.Column('Reserve_date', sa.Date(), nullable=True),
    sa.Column('Reserve_days', sa.Integer(), nullable=True),
    sa.Column('Purchase_doc', sa.String(), nullable=True),
    sa.Column('Purchase_date', sa.Date(), nullable=True),
    sa.Column('Order', sa.String(), nullable=True),
    sa.Column('k_Movement', sa.Numeric(), nullable=True),
    sa.Column('k_Storage', sa.Numeric(), nullable=True),
    sa.Column('k_Money', sa.Numeric(), nullable=True),
    sa.Column('DocType_id', sa.Integer(), nullable=True),
    sa.Column('Customer_id', sa.String(), nullable=True),
    sa.Column('Material_id', sa.String(), nullable=True),
    sa.Column('Contract_id', sa.String(), nullable=True),
    sa.Column('Supplier_id', sa.String(), nullable=True),
    sa.Column('Manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Contract_id'], ['contracts.id'], name='fk_temp_sales_orders_contract'),
    sa.ForeignKeyConstraint(['Customer_id'], ['customers.id'], name='fk_temp_sales_orders_customer'),
    sa.ForeignKeyConstraint(['DocType_id'], ['doc_type.id'], name='fk_temp_sales_orders_doctype'),
    sa.ForeignKeyConstraint(['Manager_id'], ['managers.id'], name='fk_temp_sales_orders_managers'),
    sa.ForeignKeyConstraint(['Material_id'], ['material.Code'], name='fk_temp_sales_orders_material'),
    sa.ForeignKeyConstraint(['Supplier_id'], ['suppliers.id'], name='fk_temp_sales_orders_supplier'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_temp_sales_orders'))
    )
    op.create_table('write_off',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Date_Time', sa.DateTime(), nullable=True),
    sa.Column('Document', sa.String(), nullable=True),
    sa.Column('Date', sa.Date(), nullable=True),
    sa.Column('Stock', sa.String(), nullable=True),
    sa.Column('Comment', sa.String(), nullable=True),
    sa.Column('inComing', sa.Numeric(), nullable=True),
    sa.Column('outComing', sa.Numeric(), nullable=True),
    sa.Column('Qty', sa.Numeric(), nullable=True),
    sa.Column('Reporting', sa.String(), nullable=True),
    sa.Column('Doc_based', sa.String(), nullable=True),
    sa.Column('Date_Doc_based', sa.Date(), nullable=True),
    sa.Column('Order', sa.String(), nullable=True),
    sa.Column('Shipment', sa.String(), nullable=True),
    sa.Column('Suppl_Inv_N', sa.String(), nullable=True),
    sa.Column('Bill', sa.String(), nullable=True),
    sa.Column('Bill_date', sa.Date(), nullable=True),
    sa.Column('DocType_id', sa.Integer(), nullable=True),
    sa.Column('Material_id', sa.String(), nullable=True),
    sa.Column('Supplier_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['DocType_id'], ['doc_type.id'], name='fk_writeoff_doctype'),
    sa.ForeignKeyConstraint(['Material_id'], ['material.Code'], name='fk_writeoff_material'),
    sa.ForeignKeyConstraint(['Supplier_id'], ['suppliers.id'], name='fk_writeoff_supplier'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_write_off'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('write_off')
    op.drop_table('temp_sales_orders')
    op.drop_table('temp_purchase')
    op.drop_index('idx_purchase_order_supplier', table_name='purchase_orders')
    op.drop_index('idx_purchase_order_material', table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_table('movements')
    op.drop_index('idx_marketplace_material', table_name='marketplace')
    op.drop_index('idx_marketplace_holding', table_name='marketplace')
    op.drop_index('idx_marketplace_document', table_name='marketplace')
    op.drop_index('idx_marketplace_date', table_name='marketplace')
    op.drop_table('marketplace')
    op.drop_table('complects_manual')
    op.drop_table('complects')
    op.drop_table('commission')
    op.drop_table('material')
    op.drop_index('idx_hyundai_code_unique', table_name='hyundai_dealers')
    op.drop_index('idx_dealer_code_unique', table_name='hyundai_dealers')
    op.drop_table('hyundai_dealers')
    op.drop_table('customer_plans')
    op.drop_table('contracts')
    op.drop_table('abc_cat')
    op.drop_table('taxfee')
    op.drop_table('product_names')
    op.drop_table('managers')
    op.drop_table('labling')
    op.drop_table('company_plans')
    op.drop_table('calendar')
    op.drop_table('team_leads')
    op.drop_table('suppl_schemes')
    op.drop_table('stls')
    op.drop_table('product_group')
    op.drop_table('months')
    op.drop_table('ecofee_standard')
    op.drop_table('ecofee_amount')
    op.drop_table('customs_rate')
    op.drop_table('customers')
    op.drop_table('add_suppl_cost')
    op.drop_table('years')
    op.drop_table('weeks')
    op.drop_table('tnved')
    op.drop_table('team')
    op.drop_table('suppliers')
    op.drop_table('sectors')
    op.drop_table('quarters')
    op.drop_table('product_family')
    op.drop_table('holdings')
    op.drop_table('doc_type')
    op.drop_index('idx_delivery24_sborka', table_name='delivery_to_customer_24')
    op.drop_index('idx_delivery24_inn', table_name='delivery_to_customer_24')
    op.drop_index('idx_delivery24_delivery_date', table_name='delivery_to_customer_24')
    op.drop_index('idx_delivery24_customer_name', table_name='delivery_to_customer_24')
    op.drop_index('idx_delivery24_bill_sborka', table_name='delivery_to_customer_24')
    op.drop_index('idx_delivery24_bill', table_name='delivery_to_customer_24')
    op.drop_table('delivery_to_customer_24')
    op.drop_index('idx_delivery_sborka', table_name='delivery_to_customer')
    op.drop_index('idx_delivery_inn', table_name='delivery_to_customer')
    op.drop_index('idx_delivery_delivery_date', table_name='delivery_to_customer')
    op.drop_index('idx_delivery_customer_name', table_name='delivery_to_customer')
    op.drop_index('idx_delivery_bill_sborka', table_name='delivery_to_customer')
    op.drop_index('idx_delivery_bill', table_name='delivery_to_customer')
    op.drop_table('delivery_to_customer')
    op.drop_table('abc_list')
    # ### end Alembic commands ###
