"""updated customer product table

Revision ID: 01dd0382bf5d
Revises: 0121832f6768
Create Date: 2026-01-23 13:02:44.061312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01dd0382bf5d'
down_revision: Union[str, None] = '0121832f6768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('Customer_status', sa.String(), nullable=True))
    op.add_column('material', sa.Column('Ecofee', sa.String(), nullable=True))
    op.add_column('material', sa.Column('Labling', sa.String(), nullable=True))
    op.drop_column('material', 'Family')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material', sa.Column('Family', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('material', 'Labling')
    op.drop_column('material', 'Ecofee')
    op.drop_column('customers', 'Customer_status')
    # ### end Alembic commands ###
