"""correct_naming

Revision ID: 0406623a54a5
Revises: f7440bef2bb9
Create Date: 2025-08-01 02:04:07.658986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0406623a54a5'
down_revision: Union[str, None] = 'f7440bef2bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_plans', sa.Column('Year_id', sa.Integer(), nullable=True))
    op.add_column('customer_plans', sa.Column('Month_id', sa.Integer(), nullable=True))
    op.add_column('customer_plans', sa.Column('Week_id', sa.Integer(), nullable=True))
    op.add_column('customer_plans', sa.Column('Holding_id', sa.Integer(), nullable=True))
    op.add_column('customer_plans', sa.Column('Manager_id', sa.Integer(), nullable=True))
    op.add_column('customer_plans', sa.Column('Sector_id', sa.Integer(), nullable=True))
    op.add_column('customer_plans', sa.Column('STL_id', sa.Integer(), nullable=True))
    op.add_column('customer_plans', sa.Column('TeamLead_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_customer_plans_Year_id_years', 'customer_plans', type_='foreignkey')
    op.drop_constraint('fk_customer_plans_Holding_id_holdings', 'customer_plans', type_='foreignkey')
    op.drop_constraint('fk_customer_plans_Week_id_weeks', 'customer_plans', type_='foreignkey')
    op.drop_constraint('fk_customer_plans_Month_id_months', 'customer_plans', type_='foreignkey')
    op.create_foreign_key('fk_customer_plans_Year_id_years', 'customer_plans', 'years', ['Year_id'], ['id'])
    op.create_foreign_key('fk_customer_plans_Month_id_months', 'customer_plans', 'months', ['Month_id'], ['id'])
    op.create_foreign_key('fk_customer_plans_Sector_id_sectors', 'customer_plans', 'sectors', ['Sector_id'], ['id'])
    op.create_foreign_key('fk_customer_plans_Holding_id_holdings', 'customer_plans', 'holdings', ['Holding_id'], ['id'])
    op.create_foreign_key('fk_customer_plans_Week_id_weeks', 'customer_plans', 'weeks', ['Week_id'], ['id'])
    op.create_foreign_key('fk_customer_plans_TeamLead_id_team_leads', 'customer_plans', 'team_leads', ['TeamLead_id'], ['id'])
    op.create_foreign_key('fk_customer_plans_STL_id_stls', 'customer_plans', 'stls', ['STL_id'], ['id'])
    op.create_foreign_key('fk_customer_plans_Manager_id_managers', 'customer_plans', 'managers', ['Manager_id'], ['id'])
    op.drop_column('customer_plans', 'month_id')
    op.drop_column('customer_plans', 'week_id')
    op.drop_column('customer_plans', 'year_id')
    op.drop_column('customer_plans', 'holding_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_plans', sa.Column('holding_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('customer_plans', sa.Column('year_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('customer_plans', sa.Column('week_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('customer_plans', sa.Column('month_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_customer_plans_Manager_id_managers', 'customer_plans', type_='foreignkey')
    op.drop_constraint('fk_customer_plans_STL_id_stls', 'customer_plans', type_='foreignkey')
    op.drop_constraint('fk_customer_plans_TeamLead_id_team_leads', 'customer_plans', type_='foreignkey')
    op.drop_constraint('fk_customer_plans_Week_id_weeks', 'customer_plans', type_='foreignkey')
    op.drop_constraint('fk_customer_plans_Holding_id_holdings', 'customer_plans', type_='foreignkey')
    op.drop_constraint('fk_customer_plans_Sector_id_sectors', 'customer_plans', type_='foreignkey')
    op.drop_constraint('fk_customer_plans_Month_id_months', 'customer_plans', type_='foreignkey')
    op.drop_constraint('fk_customer_plans_Year_id_years', 'customer_plans', type_='foreignkey')
    op.create_foreign_key('fk_customer_plans_Month_id_months', 'customer_plans', 'months', ['month_id'], ['id'])
    op.create_foreign_key('fk_customer_plans_Week_id_weeks', 'customer_plans', 'weeks', ['week_id'], ['id'])
    op.create_foreign_key('fk_customer_plans_Holding_id_holdings', 'customer_plans', 'holdings', ['holding_id'], ['id'])
    op.create_foreign_key('fk_customer_plans_Year_id_years', 'customer_plans', 'years', ['year_id'], ['id'])
    op.drop_column('customer_plans', 'TeamLead_id')
    op.drop_column('customer_plans', 'STL_id')
    op.drop_column('customer_plans', 'Sector_id')
    op.drop_column('customer_plans', 'Manager_id')
    op.drop_column('customer_plans', 'Holding_id')
    op.drop_column('customer_plans', 'Week_id')
    op.drop_column('customer_plans', 'Month_id')
    op.drop_column('customer_plans', 'Year_id')
    # ### end Alembic commands ###
