"""Delivery_to_Customer table created

Revision ID: 10695b00fe10
Revises: 3c4f90b9a358
Create Date: 2025-08-31 01:08:16.112856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10695b00fe10'
down_revision: Union[str, None] = '3c4f90b9a358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_to_customer_24',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Customer_name', sa.String(), nullable=True),
    sa.Column('Delivery_date', sa.Date(), nullable=True),
    sa.Column('Bill', sa.String(), nullable=True),
    sa.Column('Customer_in_logist', sa.String(), nullable=True),
    sa.Column('INN', sa.String(), nullable=True),
    sa.Column('Carrier', sa.String(), nullable=True),
    sa.Column('Sborka', sa.String(), nullable=True),
    sa.Column('Delivery_method', sa.String(), nullable=True),
    sa.Column('Delivery_amount_w_VAT', sa.Numeric(), nullable=True),
    sa.Column('Delivery_amount_wo_VAT', sa.Numeric(), nullable=True),
    sa.Column('Order_volume', sa.Numeric(), nullable=True),
    sa.Column('Comment', sa.String(), nullable=True),
    sa.Column('OZON', sa.String(), nullable=True),
    sa.Column('TS', sa.String(), nullable=True),
    sa.Column('CD_per_lt', sa.Numeric(), nullable=True),
    sa.Column('new_Amount', sa.Numeric(), nullable=True),
    sa.Column('check_Deliv_amount', sa.String(), nullable=True),
    sa.Column('inv_Volume', sa.Numeric(), nullable=True),
    sa.Column('check_Inv_volume', sa.String(), nullable=True),
    sa.Column('Invoice', sa.String(), nullable=True),
    sa.Column('Invoice_date', sa.Date(), nullable=True),
    sa.Column('Year_delivery', sa.Integer(), nullable=True),
    sa.Column('Bill_and_Date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery_to_customer_24'))
    )
    op.create_index('idx_delivery24_bill', 'delivery_to_customer_24', ['Bill'], unique=False)
    op.create_index('idx_delivery24_bill_sborka', 'delivery_to_customer_24', ['Bill', 'Sborka'], unique=False)
    op.create_index('idx_delivery24_customer_name', 'delivery_to_customer_24', ['Customer_name'], unique=False)
    op.create_index('idx_delivery24_delivery_date', 'delivery_to_customer_24', ['Delivery_date'], unique=False)
    op.create_index('idx_delivery24_inn', 'delivery_to_customer_24', ['INN'], unique=False)
    op.create_index('idx_delivery24_sborka', 'delivery_to_customer_24', ['Sborka'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_delivery24_sborka', table_name='delivery_to_customer_24')
    op.drop_index('idx_delivery24_inn', table_name='delivery_to_customer_24')
    op.drop_index('idx_delivery24_delivery_date', table_name='delivery_to_customer_24')
    op.drop_index('idx_delivery24_customer_name', table_name='delivery_to_customer_24')
    op.drop_index('idx_delivery24_bill_sborka', table_name='delivery_to_customer_24')
    op.drop_index('idx_delivery24_bill', table_name='delivery_to_customer_24')
    op.drop_table('delivery_to_customer_24')
    # ### end Alembic commands ###
