"""supplier_tables

Revision ID: 16f396644ccd
Revises: e2ede90d79c7
Create Date: 2025-08-11 10:58:07.797938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16f396644ccd'
down_revision: Union[str, None] = 'e2ede90d79c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suppl_schemes', 'Agency',
               existing_type=sa.VARCHAR(),
               type_=sa.Numeric(),
               existing_nullable=True,
               postgresql_using='"Agency"::numeric')
    
    op.alter_column('suppl_schemes', 'Re_export',
               existing_type=sa.VARCHAR(),
               type_=sa.Numeric(),
               existing_nullable=True,
               postgresql_using='"Re_export"::numeric')
    
    op.alter_column('suppl_schemes', 'Delivery',
               existing_type=sa.VARCHAR(),
               type_=sa.Numeric(),
               existing_nullable=True,
               postgresql_using='"Delivery"::numeric')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suppl_schemes', 'Delivery',
               existing_type=sa.Numeric(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    
    op.alter_column('suppl_schemes', 'Re_export',
               existing_type=sa.Numeric(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    
    op.alter_column('suppl_schemes', 'Agency',
               existing_type=sa.Numeric(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###