"""correct relationships

Revision ID: 1b5fa2c171b2
Revises: e071d0b43d7f
Create Date: 2025-08-25 10:17:48.579066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b5fa2c171b2'
down_revision: Union[str, None] = 'e071d0b43d7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_orders', sa.Column('DocType_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_temp_orders_doctype', 'temp_orders', type_='foreignkey')
    op.create_foreign_key('fk_temp_orders_doctype', 'temp_orders', 'doc_type', ['DocType_id'], ['id'])
    op.drop_column('temp_orders', 'Doc_type_id')
    op.add_column('temp_purchase', sa.Column('DocType_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_temp_purchase_doctype', 'temp_purchase', type_='foreignkey')
    op.create_foreign_key('fk_temp_purchase_doctype', 'temp_purchase', 'doc_type', ['DocType_id'], ['id'])
    op.drop_column('temp_purchase', 'Doc_type_id')
    op.add_column('temp_sales', sa.Column('DocType_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_temp_sales_doctype', 'temp_sales', type_='foreignkey')
    op.create_foreign_key('fk_temp_sales_doctype', 'temp_sales', 'doc_type', ['DocType_id'], ['id'])
    op.drop_column('temp_sales', 'Doc_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_sales', sa.Column('Doc_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_temp_sales_doctype', 'temp_sales', type_='foreignkey')
    op.create_foreign_key('fk_temp_sales_doctype', 'temp_sales', 'doc_type', ['Doc_type_id'], ['id'])
    op.drop_column('temp_sales', 'DocType_id')
    op.add_column('temp_purchase', sa.Column('Doc_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_temp_purchase_doctype', 'temp_purchase', type_='foreignkey')
    op.create_foreign_key('fk_temp_purchase_doctype', 'temp_purchase', 'doc_type', ['Doc_type_id'], ['id'])
    op.drop_column('temp_purchase', 'DocType_id')
    op.add_column('temp_orders', sa.Column('Doc_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_temp_orders_doctype', 'temp_orders', type_='foreignkey')
    op.create_foreign_key('fk_temp_orders_doctype', 'temp_orders', 'doc_type', ['Doc_type_id'], ['id'])
    op.drop_column('temp_orders', 'DocType_id')
    # ### end Alembic commands ###
