"""Marketplace created

Revision ID: 26e14512143b
Revises: e23babc03d59
Create Date: 2025-08-15 12:18:39.624833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26e14512143b'
down_revision: Union[str, None] = 'e23babc03d59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Document', sa.String(), nullable=True),
    sa.Column('Date', sa.Date(), nullable=True),
    sa.Column('Qty', sa.Numeric(), nullable=True),
    sa.Column('Amount_1C', sa.Numeric(), nullable=True),
    sa.Column('Price_1C', sa.Numeric(), nullable=True),
    sa.Column('Payment_terms', sa.String(), nullable=True),
    sa.Column('Post_payment', sa.Numeric(), nullable=True),
    sa.Column('Plan_pay_Date', sa.Date(), nullable=True),
    sa.Column('Stock', sa.String(), nullable=True),
    sa.Column('UoM', sa.String(), nullable=True),
    sa.Column('Currency', sa.String(), nullable=True),
    sa.Column('FX_rate', sa.Numeric(), nullable=True),
    sa.Column('VAT', sa.String(), nullable=True),
    sa.Column('Calendar_id', sa.Integer(), nullable=True),
    sa.Column('Material_id', sa.String(), nullable=True),
    sa.Column('Customer_id', sa.String(), nullable=True),
    sa.Column('Manager_id', sa.Integer(), nullable=True),
    sa.Column('Contract_id', sa.String(), nullable=True),
    sa.Column('Holding_id', sa.Integer(), nullable=True),
    sa.Column('Sector_id', sa.Integer(), nullable=True),
    sa.Column('DocType_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Calendar_id'], ['calendar.id'], name='fk_marketplace_calendar'),
    sa.ForeignKeyConstraint(['Contract_id'], ['contracts.id'], name='fk_marketplace_contract'),
    sa.ForeignKeyConstraint(['Customer_id'], ['customers.id'], name='fk_marketplace_customer'),
    sa.ForeignKeyConstraint(['DocType_id'], ['doc_type.id'], name='fk_marketplace_doctype'),
    sa.ForeignKeyConstraint(['Holding_id'], ['holdings.id'], name='fk_marketplace_holding'),
    sa.ForeignKeyConstraint(['Manager_id'], ['managers.id'], name='fk_marketplace_manager'),
    sa.ForeignKeyConstraint(['Material_id'], ['material.Code'], name='fk_marketplace_material'),
    sa.ForeignKeyConstraint(['Sector_id'], ['sectors.id'], name='fk_marketplace_sector'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marketplace'))
    )
    op.create_index('idx_marketplace_date', 'marketplace', ['Date'], unique=False)
    op.create_index('idx_marketplace_document', 'marketplace', ['Document'], unique=False)
    op.create_index('idx_marketplace_holding', 'marketplace', ['Holding_id'], unique=False)
    op.create_index('idx_marketplace_material', 'marketplace', ['Material_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_marketplace_material', table_name='marketplace')
    op.drop_index('idx_marketplace_holding', table_name='marketplace')
    op.drop_index('idx_marketplace_document', table_name='marketplace')
    op.drop_index('idx_marketplace_date', table_name='marketplace')
    op.drop_table('marketplace')
    # ### end Alembic commands ###
