"""change relationships ProdName and Materials

Revision ID: 2757f9afa0ac
Revises: 7f32e611d97d
Create Date: 2025-02-09 18:20:59.571895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2757f9afa0ac'
down_revision: Union[str, None] = '7f32e611d97d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
