"""Delivery_to_Customer table created

Revision ID: 3c4f90b9a358
Revises: f510a0b54a08
Create Date: 2025-08-31 01:07:05.303128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c4f90b9a358'
down_revision: Union[str, None] = 'f510a0b54a08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_to_customer', 'Year_invoice')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_to_customer', sa.Column('Year_invoice', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
