"""Hyundai_Dealer correct

Revision ID: 51c99ecf0071
Revises: c2fea150d8bf
Create Date: 2025-08-20 22:40:01.203551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51c99ecf0071'
down_revision: Union[str, None] = 'c2fea150d8bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
