"""delivery added new_Comment

Revision ID: 62532bd79f21
Revises: d8fecaa4e596
Create Date: 2025-09-01 18:05:58.886796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62532bd79f21'
down_revision: Union[str, None] = 'd8fecaa4e596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_to_customer', sa.Column('new_Comment', sa.String(), nullable=True))
    op.drop_column('delivery_to_customer_24', 'сarrier')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_to_customer_24', sa.Column('сarrier', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('delivery_to_customer', 'new_Comment')
    # ### end Alembic commands ###
