"""fix_abc_relations

Revision ID: 72dba3b6a503
Revises: ff5153bc6b42
Create Date: 2025-07-27 14:07:48.016866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72dba3b6a503'
down_revision: Union[str, None] = 'ff5153bc6b42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_names', sa.Column('Product_name', sa.String(), nullable=False))
    op.drop_constraint('uq_product_names_Product_names', 'product_names', type_='unique')
    op.create_unique_constraint(op.f('uq_product_names_Product_name'), 'product_names', ['Product_name'])
    op.drop_column('product_names', 'Product_names')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_names', sa.Column('Product_names', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('uq_product_names_Product_name'), 'product_names', type_='unique')
    op.create_unique_constraint('uq_product_names_Product_names', 'product_names', ['Product_names'])
    op.drop_column('product_names', 'Product_name')
    # ### end Alembic commands ###
