"""add_clmn_Status_to_Material

Revision ID: 83e0d7061896
Revises: c19bc24f6ba8
Create Date: 2025-08-08 16:35:47.083168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83e0d7061896'
down_revision: Union[str, None] = 'c19bc24f6ba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material', sa.Column('Status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material', 'Status')
    # ### end Alembic commands ###
