"""change purchase_order

Revision ID: a3e799847f80
Revises: 1b5fa2c171b2
Create Date: 2025-08-29 18:53:43.693036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3e799847f80'
down_revision: Union[str, None] = '1b5fa2c171b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_purchase_order_unique', table_name='purchase_orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_purchase_order_unique', 'purchase_orders', ['Order', 'Document', 'Date'], unique=True)
    # ### end Alembic commands ###
