"""empty message

Revision ID: a872c96c2952
Revises: 4bfd3cbdfdda
Create Date: 2025-02-08 23:37:02.190849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a872c96c2952'
down_revision: Union[str, None] = '4bfd3cbdfdda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecofee_amount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merge', sa.String(), nullable=True),
    sa.Column('TNVED', sa.String(), nullable=True),
    sa.Column('Year', sa.Integer(), nullable=True),
    sa.Column('Amount', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('taxfee', schema=None) as batch_op:
        batch_op.drop_column('Eco_norm')
        batch_op.drop_column('Eco_Fee')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taxfee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Eco_Fee', sa.NUMERIC(), nullable=True))
        batch_op.add_column(sa.Column('Eco_norm', sa.NUMERIC(), nullable=True))

    op.drop_table('ecofee_amount')
    # ### end Alembic commands ###
