"""supplier_tables

Revision ID: b8568c21e5a2
Revises: 83e0d7061896
Create Date: 2025-08-10 12:45:55.039904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8568c21e5a2'
down_revision: Union[str, None] = '83e0d7061896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('Supplier_Name', sa.String(), nullable=True),
    sa.Column('Full_Suppl_name', sa.String(), nullable=True),
    sa.Column('Imp_Loc', sa.String(), nullable=True),
    sa.Column('Customs', sa.String(), nullable=True),
    sa.Column('Movement', sa.String(), nullable=True),
    sa.Column('Country', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers'))
    )
    op.create_table('suppl_schemes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('Supplier1', sa.String(), nullable=True),
    sa.Column('Country', sa.String(), nullable=True),
    sa.Column('Supplier2', sa.String(), nullable=True),
    sa.Column('Supplier_id', sa.String(), nullable=True),
    sa.Column('Supplier_Name_report', sa.String(), nullable=True),
    sa.Column('Agency', sa.String(), nullable=True),
    sa.Column('Re_export', sa.String(), nullable=True),
    sa.Column('Delivery', sa.String(), nullable=True),
    sa.Column('Comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['Supplier_id'], ['suppliers.id'], name='fk_scheme_supplier'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppl_schemes'))
    )
    op.drop_table('supplier')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Supplier_Name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Imp_Loc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Customs', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_supplier')
    )
    op.drop_table('suppl_schemes')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
