"""fixed_naming

Revision ID: c19bc24f6ba8
Revises: 0406623a54a5
Create Date: 2025-08-08 11:31:12.399142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c19bc24f6ba8'
down_revision: Union[str, None] = '0406623a54a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_customer_plan_unique', 'customer_plans', ['Year_id', 'Month_id', 'Week_id', 'Holding_id', 'Manager_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_customer_plan_unique', 'customer_plans', type_='unique')
    # ### end Alembic commands ###
