"""correct doctype

Revision ID: c2fea150d8bf
Revises: 0e53cf2dfaf3
Create Date: 2025-08-20 19:56:25.333876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2fea150d8bf'
down_revision: Union[str, None] = '0e53cf2dfaf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doc_type', 'merge')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc_type', sa.Column('merge', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
