"""empty message

Revision ID: d43939a36450
Revises: a872c96c2952
Create Date: 2025-02-08 23:39:03.919898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd43939a36450'
down_revision: Union[str, None] = 'a872c96c2952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecofee_standard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merge', sa.String(), nullable=True),
    sa.Column('TNVED', sa.String(), nullable=True),
    sa.Column('Year', sa.Integer(), nullable=True),
    sa.Column('Standard', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ecofee_standard')
    # ### end Alembic commands ###
