"""Delivery_to_Customer table created

Revision ID: d8fecaa4e596
Revises: 10695b00fe10
Create Date: 2025-08-31 01:49:56.291764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8fecaa4e596'
down_revision: Union[str, None] = '10695b00fe10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_to_customer_24', 'сarrier')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_to_customer_24', sa.Column('сarrier', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
