"""fix_abc_relations

Revision ID: dbd74187c4d2
Revises: b6b359a54689
Create Date: 2025-07-27 12:57:04.831993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbd74187c4d2'
down_revision: Union[str, None] = 'b6b359a54689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abc_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ABC_category', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_abc_list')),
    sa.UniqueConstraint('ABC_category', name=op.f('uq_abc_list_ABC_category'))
    )
    op.add_column('abc_cat', sa.Column('abc_list_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_abc_cat_abc_list', 'abc_cat', 'abc_list', ['abc_list_id'], ['id'])
    op.drop_column('abc_cat', 'ABC_category')
    op.add_column('company_plans', sa.Column('abc_category_id', sa.Integer(), nullable=True))
    op.alter_column('company_plans', 'calendar_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key('fk_company_plan_abc_category', 'company_plans', 'abc_list', ['abc_category_id'], ['id'])
    op.drop_column('company_plans', 'ABC')
    op.alter_column('customer_plans', 'calendar_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_plans', 'calendar_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('company_plans', sa.Column('ABC', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_company_plan_abc_category', 'company_plans', type_='foreignkey')
    op.alter_column('company_plans', 'calendar_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('company_plans', 'abc_category_id')
    op.add_column('abc_cat', sa.Column('ABC_category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_abc_cat_abc_list', 'abc_cat', type_='foreignkey')
    op.drop_column('abc_cat', 'abc_list_id')
    op.drop_table('abc_list')
    # ### end Alembic commands ###
