"""change costs - added okleyka

Revision ID: de5c89d0db49
Revises: 62532bd79f21
Create Date: 2025-09-05 16:30:01.328787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de5c89d0db49'
down_revision: Union[str, None] = '62532bd79f21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxfee', sa.Column('Okleyka', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taxfee', 'Okleyka')
    # ### end Alembic commands ###
