"""table AddSupplCost correct

Revision ID: e23babc03d59
Revises: 80984505661e
Create Date: 2025-08-11 16:38:56.914954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e23babc03d59'
down_revision: Union[str, None] = '80984505661e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('add_suppl_cost',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Document', sa.String(), nullable=True),
    sa.Column('Date', sa.Date(), nullable=True),
    sa.Column('Supplier_id', sa.String(), nullable=True),
    sa.Column('Supplier_Name_report', sa.String(), nullable=True),
    sa.Column('Supplier1', sa.String(), nullable=True),
    sa.Column('Supplier2', sa.String(), nullable=True),
    sa.Column('Order', sa.String(), nullable=True),
    sa.Column('Shipment', sa.String(), nullable=True),
    sa.Column('Container', sa.String(), nullable=True),
    sa.Column('Suppl_Inv_N', sa.String(), nullable=True),
    sa.Column('Storage', sa.String(), nullable=True),
    sa.Column('Imp_Loc', sa.String(), nullable=True),
    sa.Column('Movement', sa.String(), nullable=True),
    sa.Column('Volume', sa.Numeric(), nullable=True),
    sa.Column('First_Invoice_Amount', sa.Numeric(), nullable=True),
    sa.Column('Final_Invoice_Amount', sa.Numeric(), nullable=True),
    sa.Column('GTD_doc', sa.String(), nullable=True),
    sa.Column('Status', sa.String(), nullable=True),
    sa.Column('Currency', sa.String(), nullable=True),
    sa.Column('Payment_FX', sa.Numeric(), nullable=True),
    sa.Column('Load_Unload', sa.Numeric(), nullable=True),
    sa.Column('Agency', sa.Numeric(), nullable=True),
    sa.Column('Transport_mn', sa.Numeric(), nullable=True),
    sa.Column('Transport_loc', sa.Numeric(), nullable=True),
    sa.Column('Add_Services', sa.Numeric(), nullable=True),
    sa.Column('Commission', sa.Numeric(), nullable=True),
    sa.Column('Comment', sa.String(), nullable=True),
    sa.Column('Transp_VED', sa.Numeric(), nullable=True),
    sa.Column('Transp_FX', sa.Numeric(), nullable=True),
    sa.Column('Customs_date', sa.Date(), nullable=True),
    sa.Column('Date_arrival', sa.Date(), nullable=True),
    sa.Column('Carrier', sa.String(), nullable=True),
    sa.Column('Carrier_orders', sa.String(), nullable=True),
    sa.Column('merge_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['Supplier_id'], ['suppliers.id'], name=op.f('fk_add_suppl_cost_Supplier_id_suppliers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_add_suppl_cost')),
    sa.UniqueConstraint('merge_id', name=op.f('uq_add_suppl_cost_merge_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('add_suppl_cost')
    # ### end Alembic commands ###
