"""correct supplier table

Revision ID: e2ede90d79c7
Revises: b8568c21e5a2
Create Date: 2025-08-11 10:02:02.365622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2ede90d79c7'
down_revision: Union[str, None] = 'b8568c21e5a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suppl_schemes', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               postgresql_using='id::integer')  # Добавлено явное преобразование
    op.create_unique_constraint(op.f('uq_suppl_schemes_Supplier_Name_report'), 'suppl_schemes', ['Supplier_Name_report'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_suppl_schemes_Supplier_Name_report'), 'suppl_schemes', type_='unique')
    op.alter_column('suppl_schemes', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###