"""fix_abc_relations

Revision ID: e4fd75aa30e9
Revises: ba34e5d737f3
Create Date: 2025-07-27 13:17:53.636727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4fd75aa30e9'
down_revision: Union[str, None] = 'ba34e5d737f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
