"""Delivery_to_Customer table created

Revision ID: f510a0b54a08
Revises: a3e799847f80
Create Date: 2025-08-30 22:45:44.580975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f510a0b54a08'
down_revision: Union[str, None] = 'a3e799847f80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_to_customer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Customer_name', sa.String(), nullable=True),
    sa.Column('Delivery_date', sa.Date(), nullable=True),
    sa.Column('Bill', sa.String(), nullable=True),
    sa.Column('Customer_in_logist', sa.String(), nullable=True),
    sa.Column('INN', sa.String(), nullable=True),
    sa.Column('Carrier', sa.String(), nullable=True),
    sa.Column('Sborka', sa.String(), nullable=True),
    sa.Column('Delivery_method', sa.String(), nullable=True),
    sa.Column('Delivery_amount_w_VAT', sa.Numeric(), nullable=True),
    sa.Column('Delivery_amount_wo_VAT', sa.Numeric(), nullable=True),
    sa.Column('Order_volume', sa.Numeric(), nullable=True),
    sa.Column('Comment', sa.String(), nullable=True),
    sa.Column('OZON', sa.String(), nullable=True),
    sa.Column('TS', sa.String(), nullable=True),
    sa.Column('CD_per_lt', sa.Numeric(), nullable=True),
    sa.Column('new_Amount', sa.Numeric(), nullable=True),
    sa.Column('check_Deliv_amount', sa.String(), nullable=True),
    sa.Column('inv_Volume', sa.Numeric(), nullable=True),
    sa.Column('check_Inv_volume', sa.String(), nullable=True),
    sa.Column('Invoice', sa.String(), nullable=True),
    sa.Column('Invoice_date', sa.Date(), nullable=True),
    sa.Column('Year_invoice', sa.Integer(), nullable=True),
    sa.Column('Year_delivery', sa.Integer(), nullable=True),
    sa.Column('Bill_and_Date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery_to_customer'))
    )
    op.create_index('idx_delivery_bill', 'delivery_to_customer', ['Bill'], unique=False)
    op.create_index('idx_delivery_bill_sborka', 'delivery_to_customer', ['Bill', 'Sborka'], unique=False)
    op.create_index('idx_delivery_customer_name', 'delivery_to_customer', ['Customer_name'], unique=False)
    op.create_index('idx_delivery_delivery_date', 'delivery_to_customer', ['Delivery_date'], unique=False)
    op.create_index('idx_delivery_inn', 'delivery_to_customer', ['INN'], unique=False)
    op.create_index('idx_delivery_sborka', 'delivery_to_customer', ['Sborka'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_delivery_sborka', table_name='delivery_to_customer')
    op.drop_index('idx_delivery_inn', table_name='delivery_to_customer')
    op.drop_index('idx_delivery_delivery_date', table_name='delivery_to_customer')
    op.drop_index('idx_delivery_customer_name', table_name='delivery_to_customer')
    op.drop_index('idx_delivery_bill_sborka', table_name='delivery_to_customer')
    op.drop_index('idx_delivery_bill', table_name='delivery_to_customer')
    op.drop_table('delivery_to_customer')
    # ### end Alembic commands ###
